### ISSUE TITLE
source-filesystem: due creating nodes from files at random, the build ends up with different hashes despite content having not changed

### ISSUE THREAD

**Issue by tstriker** [gridsome/gridsome#1247]
I'm using `source-filesystem` plugin to get contents from a dozen content files and generate a page using graphQL. 

I noticed that the build hash after `runWebpack` is finished
here https://github.com/gridsome/gridsome/blob/master/gridsome/lib/build.js#L24 kept changing all the time, despite not having changed the files.

Tracked it down to here:
https://github.com/gridsome/gridsome/blob/master/packages/source-filesystem/index.js#L60-L71

the files are globbed and then read all at once, and the order the `.addNode` function will be called will be somewhat random.
It seems that that results in the hash changing.

i've put in a kludge on my local build to fix the behavior:

```javascript
  async createNodes (actions) {
    const glob = require('globby')

    const files = await (await glob(this.options.path, { cwd: this.context })).sort()


    let allOptions = [];
    await Promise.all(files.map(async file => {
      const options = await this.createNodeOptions(file, actions)
      allOptions.push(options);
    }))


    allOptions.sort((a, b) => a.fileInfo.path > b.fileInfo.path ? 1 : -1);
    allOptions.forEach(options =>{
        const node = this.collection.addNode(options)
        this.createNodeRefs(node, actions)
    });
  }
```

The app hash is added to the headers of all files as well as appended to the app.js filename, and so, deploying twice even without changing any files, will result in cache busting.

The expectation is for the hash to be deterministic - same input should yield same output. 
Sorting the files before calling `addNode` seems to do the job, but i'm not too familiar with the inner workings and maybe the actual fix needs to go someplace deeper.

**Comment by hjvedvik** [comment]
Thanks for debugging this, @tstriker. I did some more tests yesterday and noticed that the order of the nodes affected the `routes.js` file in some cases. I fixed that by sorting the routes by priority, then the path.

And the webpack loader for `page-query` generates no code, which is correct. But results in a very random behavior where it sometimes is replaced with a boolean and some other times with a module from webpack. But I get a consistent build by just making it generate `export default null`.

At least, I get the same hash every time when building gridsome.org after these changes :)

**Comment by AllanChain** [comment]
But I am still getting different hashes when building gridsome.org with gridsome v0.7.20 😕 What's wrong?

**Comment by S-Traut** [comment]
https://github.com/gridsome/gridsome/commit/da5674fd248fd518963328628d578c0c93451d95#r62290122
